import { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css'
import getData from './api/databaseFetch';


export default function Home() {

  // Data State
  const [data, setData] = useState([]);
  const [isLoading, setLoading] = useState(false);

  // Data Fetching
  useEffect(() => {
    setLoading(true);
    getData().then((res) => {     
      setData(res);
    }).finally(() => setLoading(false));
  }, []);

  return (
    <>
      <Head>
        <title>Sentics Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* Navigation Section */}
        <div className={styles.navbar}>
          <div style={{
            padding: '1rem',
            backgroundColor: '#B92736'
          }}>
              <div className={styles.title}>
                Quality Monitor
              </div>
              <div className={styles.subtitle}>
                Dashboard
              </div>
          </div>
          <div style={{
            padding: '1rem',
            backgroundColor: '#871D27'
          }}>
              <code>Scanned Parts</code>
          </div>
          <div className={styles.partList}>
              {
                data.map((part) => (
                  <div 
                   key={part['PID']} className={styles.card}
                   onClick={(el) => {
                    console.log(el);
                   }}
                  >
                    <code>{part['PID']}</code><br/>
                    <code style={{
                      fontSize: 10
                    }}>Cracks : {Object(part['cracks']).length}</code>
                  </div>
                 )
                )
              }
          </div>
          <div style={{
            backgroundImage: 'linear-gradient(#0D1A30, #040910)',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'flex-end',
            padding: '1rem',
            margin: 0,
          }}>
              <div className={styles.subtitle}>
                Powered by
              </div>
              <img
                  src={'/images/logo.png'}
                  alt='logo'
                  height={'auto'}
                  style={{
                    maxWidth:'70%',
                    marginTop: '-50px',
                  }}
              />
          </div>
        </div>
        <div className={styles.appbody}>
          
        </div>
      </main>
    </>
  )
}
